// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ96j0euaEZZyx5Yy1dCpsbUICEklzkLQ',
    appId: '1:139067419463:web:ab659908c7e3bcc9ddfa62',
    messagingSenderId: '139067419463',
    projectId: 'meal-app-login',
    authDomain: 'meal-app-login.firebaseapp.com',
    databaseURL: 'https://meal-app-login-default-rtdb.firebaseio.com',
    storageBucket: 'meal-app-login.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFxAyzeI96zZgYDNbG_PafPv01CLbp-ls',
    appId: '1:139067419463:android:5e581d5e9688d02eddfa62',
    messagingSenderId: '139067419463',
    projectId: 'meal-app-login',
    databaseURL: 'https://meal-app-login-default-rtdb.firebaseio.com',
    storageBucket: 'meal-app-login.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLP2bL98ZgKIciAq0d7SQoSUsNnAoFeoI',
    appId: '1:139067419463:ios:a3fb007e4adfc3f6ddfa62',
    messagingSenderId: '139067419463',
    projectId: 'meal-app-login',
    databaseURL: 'https://meal-app-login-default-rtdb.firebaseio.com',
    storageBucket: 'meal-app-login.appspot.com',
    iosBundleId: 'com.example.latestMealAppRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLP2bL98ZgKIciAq0d7SQoSUsNnAoFeoI',
    appId: '1:139067419463:ios:e061c134d0df21aaddfa62',
    messagingSenderId: '139067419463',
    projectId: 'meal-app-login',
    databaseURL: 'https://meal-app-login-default-rtdb.firebaseio.com',
    storageBucket: 'meal-app-login.appspot.com',
    iosBundleId: 'com.example.latestMealAppRiverpod.RunnerTests',
  );
}
